"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _right_panel_balance_overview from './right-panel-balance-overview.bones.json'
import _right_panel_total_balance from './right-panel-total-balance.bones.json'
import _header_display_name from './header-display-name.bones.json'
import _expense_list from './expense-list.bones.json'
import _right_panel_members_list_1 from './right-panel-members-list-1.bones.json'
import _profile_popup_image from './profile-popup-image.bones.json'
import _profile_popup_name from './profile-popup-name.bones.json'
import _profile_popup_phone from './profile-popup-phone.bones.json'
import _profile_popup_upi from './profile-popup-upi.bones.json'
import _right_panel_members_list from './right-panel-members-list.bones.json'
import _split_expense_assigned_amount from './split-expense-assigned-amount.bones.json'
import _split_expense_member_row from './split-expense-member-row.bones.json'

registerBones({
  "right-panel-balance-overview": _right_panel_balance_overview,
  "right-panel-total-balance": _right_panel_total_balance,
  "header-display-name": _header_display_name,
  "expense-list": _expense_list,
  "right-panel-members-list-1": _right_panel_members_list_1,
  "profile-popup-image": _profile_popup_image,
  "profile-popup-name": _profile_popup_name,
  "profile-popup-phone": _profile_popup_phone,
  "profile-popup-upi": _profile_popup_upi,
  "right-panel-members-list": _right_panel_members_list,
  "split-expense-assigned-amount": _split_expense_assigned_amount,
  "split-expense-member-row": _split_expense_member_row,
})
